import { ApiProperty } from "@nestjs/swagger";
import { IsNumber, IsString, IsEmail, IsBoolean, IsDecimal } from "class-validator";

export class SubscriptionPlanDto {

    @IsString()
    @ApiProperty({ example: '12433', description: 'User ID' })
    userId?: number;

    @IsString()
    @ApiProperty({ example: '06915bf3937841a794de11668ff6c811', description: 'Subscription ID generated by Mercado Pago' })
    mercadoLivreSubscriptionId: string; 

    @IsString()
    @ApiProperty({ example: '1842483954', description: 'Payer ID generated by Mercado Pago' })
    mercadoLivrePayerId: string; 

    @IsString()
    @ApiProperty({ example: 'https://www.mercadopago.com.br/subscriptions/checkout?preapproval_id=06915bf3937841a794de11668ff6c811', description: 'Payment URL generated by Mercado Pago' })
    paymentUrl?: string; 

    @IsString()
    @ApiProperty({ example: 'Capti Plano A', description: 'Subscrition plan name' })
    planName?: string;  

    @IsString()
    @ApiProperty({ example: '2024-06-07T08:15:24.424-04:00', description: 'Date of subscription creation' })
    creationDate: string;

    @IsString()
    @ApiProperty({ example: '2024-06-08T08:15:24.424-04:00', description: 'Date of subscription payment start' })
    paymentStartDate: string;

    @IsDecimal()
    @ApiProperty({ example: '49.9', description: 'Subscription plan value' })
    value: number;

    @IsString()
    @ApiProperty({ example: 'authorized', description: 'Status of the subscription plan' })
    status: string;
    
    @IsBoolean()
    @ApiProperty({ example: 'true', description: 'State of the subscription plan' })
    active : boolean;

}